<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.0 setup script
 * Date: Thu, 27 May 2021 09:34:48 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: sddb0040015847.cgidb [1] */
$i++;
$cfg['CheckConfigurationPermissions'] = false;
$cfg['Servers'][$i]['verbose'] = 'sddb0040030286.cgidb';
$cfg['Servers'][$i]['host'] = 'sddb0040030286.cgidb';
$cfg['Servers'][$i]['port'] = 'root';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = 'root';
$cfg['Servers'][$i]['only_db'] = array('sddb0040030286');

/* End of servers configuration */

$cfg['blowfish_secret'] = 'o8>6+[9tfRu46Y[,.A-*~TGaE4"\\{upr';
$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>